const cards = [
  {
    type: "podcast",
    text: "Ann Roberson introduces OpStar in this discussion with Daniel Hickman",
    cover: "star_cover.jpg",
    content: "star_content.jpg",
    logo: "star_logo.png",
    real: "opstartsep1pt1.mp3",
  },
  {
    type: "podcast",
    text: "Nancy talks about silver linings amind the chaos",
    cover: "vendor_cover.jpg",
    content: "vendor_content.jpg",
    logo: "vendor_logo.png",
    real: "testSound.mp3",
  },
  {
    type: "podcast",
    text: "CeCe shares how it changed her world",
    cover: "cancer_cover.jpg",
    content: "cancer_content.jpg",
    logo: "cancer_logo.png",
    real: "testSound.mp3",
  },
  {
    type: "podcast",
    text: "Ann shares stories from her journey",
    cover: "ann_cover.jpg",
    content: "ann_content.jpg",
    logo: "ann_logo.png",
    real: "testSound.mp3",
  },
  {
    type: "podcast",
    text: "Keith shares his experience of 2021 Texas power crises",
    cover: "outage_cover.jpg",
    content: "outage_content.jpg",
    logo: "outage_logo.png",
    real: "testSound.mp3",
  },
  {
    type: "podcast",
    text: "How Aaron got his Greenbelt",
    cover: "sigma_cover.jpg",
    content: "sigma_content.jpg",
    logo: "sigma_logo.png",
    real: "testSound.mp3",
  },
  {
    type: "podcast",
    text: "Nancy shares team challenges with remote work arrangement",
    cover: "remote_cover.jpg",
    content: "remote_content.jpg",
    logo: "remote_logo.png",
    real: "testSound.mp3",
  },
  {
    type: "podcast",
    text: "Juan shares how to prepare for skip-level meetings",
    cover: "skip_cover.jpg",
    content: "skip_content.jpg",
    logo: "skip_logo.png",
    real: "testSound.mp3",
  },
  {
    type: "podcast",
    text: "Bill shares his insights on process improvement and refinement",
    cover: "process_cover.jpg",
    content: "process_content.jpg",
    logo: "process_logo.png",
    real: "testSound.mp3",
  },
  {
    type: "podcast",
    text: "Juan shares his views on the ultimate mantra : Performance, Accountability, Change, Transparency",
    cover: "pact_cover.jpg",
    content: "pact_content.jpg",
    logo: "pact_logo.png",
    real: "testSound.mp3",
  },
  {
    type: "podcast",
    text: "Bill shares how it all started",
    cover: "print_cover.jpg",
    content: "print_content.jpg",
    logo: "print_logo.png",
    real: "testSound.mp3",
  },
  {
    type: "podcast",
    text: "Juan shares learnings from managing work across multiple BU's",
    cover: "multiple_cover.jpg",
    content: "multiple_content.jpg",
    logo: "multiple_logo.png",
    real: "testSound.mp3",
  },
  {
    type: "video",
    text: "Ann Roberson introduces OpStars as a platform for sharing stories",
    cover: "intro_cover.jpg",
    content: "Opstar.mp4",
    logo: "star_logo.png",
    real: "Opstar.mp4",
  },

];
